Repository gluster/glusterdocs, pull requests merged in 2020-02, with the labels that each got.

#532 Remove note on thin arbiter volumes only supported in GD2
  docs/Administrator Guide/Thin-Arbiter-Volumes.md
Labels: documentation

#533 Changes to architecture doc
  docs/Quick-Start-Guide/Architecture.md
Labels: documentation

#535 Minor change to page
  docs/Install-Guide/Common_criteria.md
Labels: documentation

#538 Removed sections for striped volumes
  docs/Quick-Start-Guide/Architecture.md
Labels: bug, documentation

#499 Docs updates
  docs/Administrator Guide/GlusterFS Introduction.md
  docs/Administrator Guide/Setting Up Volumes.md
  docs/Administrator Guide/Storage Pools.md
  docs/Developer-guide/Developers-Index.md
  docs/Install-Guide/Setup_Bare_metal.md
  docs/Install-Guide/Setup_virt.md
  docs/Quick-Start-Guide/Architecture.md
Labels: documentation, enhancement
